# Generated by Django 5.0.1 on 2025-10-31 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100, unique=True, verbose_name='Pseudônimo')),
                ('valete_profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Perfil Valete')),
                ('valete_link', models.URLField(blank=True, null=True, verbose_name='URL Valete')),
                ('substack_profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Perfil Substack')),
                ('substack_url', models.URLField(blank=True, null=True, verbose_name='URL Substack')),
                ('topics', models.TextField(blank=True, help_text='Tópicos separados por vírgula', verbose_name='Tópicos Abordados')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Escrita',
                'verbose_name_plural': 'Perfis de Escrita',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('topic', models.CharField(max_length=100, verbose_name='Tópico')),
                ('publish_date', models.DateTimeField(verbose_name='Data de Publicação')),
                ('url', models.URLField(verbose_name='URL')),
                ('platform', models.CharField(choices=[('valete', 'Valete'), ('substack', 'Substack')], max_length=20, verbose_name='Plataforma')),
                ('content_preview', models.TextField(blank=True, verbose_name='Preview do Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('coauthors', models.ManyToManyField(blank=True, related_name='postagens_como_coautor', to='core.writerprofile', verbose_name='Coautores')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='core.writerprofile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
                'ordering': ['-publish_date'],
                'unique_together': {('profile', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Formato: YYYY-MM', max_length=7, verbose_name='Mês de Referência')),
                ('month_posts', models.IntegerField(default=0, verbose_name='Postagens no Mês')),
                ('days_frequency', models.FloatField(blank=True, help_text='Média de dias entre postagens', null=True, verbose_name='Frequência Média (dias)')),
                ('total_posts', models.IntegerField(default=0, verbose_name='Total de Postagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='core.writerprofile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-month'],
                'unique_together': {('profile', 'month')},
            },
        ),
    ]
